"""Security Event ORM Entity.

Immutable detection record capturing the ML predictions, anomaly indicators,
and forensic 48-feature snapshot.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any, Dict, Optional
from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Index, Integer, JSON, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, GUID, TimestampMixin

if TYPE_CHECKING:
    from app.db.models.alert import Alert
    from app.db.models.analysis_job import AnalysisJob
    from app.db.models.flow_provenance import FlowProvenance
    from app.db.models.model_decision import ModelDecision


class SecurityEvent(Base, TimestampMixin):
    """Immutable detection record generated by the ML and Hybrid Risk Engine."""

    __tablename__ = "security_events"

    id: Mapped[uuid.UUID] = mapped_column(
        GUID(),
        primary_key=True,
        default=uuid.uuid4,
    )
    job_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        GUID(),
        ForeignKey("analysis_jobs.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    
    event_timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
        index=True,
    )
    source_channel: Mapped[str] = mapped_column(
        String(32),
        default="PCAP_BATCH",
        nullable=False,
        index=True,
    )  # PCAP_BATCH, REST_EVAL, LIVE_ZEEK

    # Primary relational detection attributes (used for all indexing and range filtering)
    predicted_family: Mapped[Optional[str]] = mapped_column(String(64), nullable=True, index=True)
    class_confidence: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    normalized_anomaly_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    is_statistical_anomaly: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False, index=True)
    risk_score: Mapped[Optional[int]] = mapped_column(Integer, nullable=True, index=True)
    severity: Mapped[Optional[str]] = mapped_column(String(32), nullable=True, index=True)  # LOW, MEDIUM, HIGH, CRITICAL
    triage_status: Mapped[Optional[str]] = mapped_column(String(32), nullable=True, index=True)  # NORMAL, UNKNOWN_ANOMALY, KNOWN_ATTACK

    ml_classification_performed: Mapped[bool] = mapped_column(
        Boolean, default=True, nullable=False, index=True,
    )

    # Complex JSON payload attributes (immutable forensic snapshot, not for primary range queries)
    class_probabilities: Mapped[Optional[Dict[str, float]]] = mapped_column(JSON, nullable=True)
    feature_vector: Mapped[Optional[Dict[str, float]]] = mapped_column(JSON, nullable=True)

    # Relationships
    job: Mapped[Optional[AnalysisJob]] = relationship("AnalysisJob", back_populates="events")
    provenance: Mapped[Optional[FlowProvenance]] = relationship(
        "FlowProvenance",
        back_populates="event",
        uselist=False,
        cascade="all, delete-orphan",
    )
    decision: Mapped[Optional[ModelDecision]] = relationship(
        "ModelDecision",
        back_populates="event",
        uselist=False,
        cascade="all, delete-orphan",
    )
    alert: Mapped[Optional[Alert]] = relationship(
        "Alert",
        back_populates="event",
        uselist=False,
        cascade="all, delete-orphan",
    )


# Multi-column composite indexes for high-volume SOC filtering
Index("ix_security_events_time_severity", SecurityEvent.event_timestamp.desc(), SecurityEvent.severity)
Index("ix_security_events_time_family", SecurityEvent.event_timestamp.desc(), SecurityEvent.predicted_family)
Index("ix_security_events_time_status", SecurityEvent.event_timestamp.desc(), SecurityEvent.triage_status)
