import React, { useEffect, useState } from 'react';
import { ShieldAlert, AlertTriangle, CheckCircle2, Clock, Filter, ArrowRight, UserCheck, MessageSquare, History, X } from 'lucide-react';
import { alertsApi, AlertSearchParams } from '../../api/alertsApi';
import { AlertDetail, AlertSummary } from '../../types/alerts';
import { SeverityBadge } from '../common/Badge';
import { LoadingSpinner } from '../common/LoadingState';
import { ErrorAlert } from '../common/ErrorAlert';
import { ApiError } from '../../api/client';
import { formatPercent } from '../../utils/formatters';

export const AlertsView: React.FC = () => {
  const [alerts, setAlerts] = useState<AlertSummary[]>([]);
  const [totalAlerts, setTotalAlerts] = useState(0);
  const [page, setPage] = useState(1);
  const [pageSize] = useState(25);
  const [totalPages, setTotalPages] = useState(1);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<ApiError | null>(null);

  // Filters
  const [selectedDisposition, setSelectedDisposition] = useState<string>('all');
  const [selectedSeverity, setSelectedSeverity] = useState<string>('all');

  // Selected Alert for Detail / Disposition Update Modal
  const [selectedAlertDetail, setSelectedAlertDetail] = useState<AlertDetail | null>(null);
  const [isLoadingDetail, setIsLoadingDetail] = useState(false);
  const [isUpdating, setIsUpdating] = useState(false);

  // Update Form State
  const [newDisposition, setNewDisposition] = useState<string>('INVESTIGATING');
  const [analystActor, setAnalystActor] = useState<string>('soc_analyst_1');
  const [analystNote, setAnalystNote] = useState<string>('');

  const fetchAlerts = async () => {
    setIsLoading(true);
    setError(null);
    try {
      const params: AlertSearchParams = {
        page,
        page_size: pageSize,
      };
      if (selectedDisposition !== 'all') {
        params.disposition = [selectedDisposition];
      }
      if (selectedSeverity !== 'all') {
        params.severity = [selectedSeverity];
      }

      const res = await alertsApi.getAlerts(params);
      setAlerts(res.items);
      setTotalAlerts(res.total);
      setTotalPages(res.total_pages);
    } catch (err: any) {
      setError(err);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchAlerts();
  }, [page, selectedDisposition, selectedSeverity]);

  const handleOpenDetail = async (alertId: string) => {
    setIsLoadingDetail(true);
    try {
      const detail = await alertsApi.getAlertDetail(alertId);
      setSelectedAlertDetail(detail);
      setNewDisposition(detail.disposition);
      setAnalystNote('');
    } catch (err: any) {
      setError(err);
    } finally {
      setIsLoadingDetail(false);
    }
  };

  const handleUpdateDisposition = async () => {
    if (!selectedAlertDetail) return;
    setIsUpdating(true);
    try {
      const updated = await alertsApi.updateDisposition(selectedAlertDetail.id, {
        new_disposition: newDisposition,
        actor_id: analystActor,
        note: analystNote || undefined,
      });
      setSelectedAlertDetail(updated);
      fetchAlerts(); // Refresh list
    } catch (err: any) {
      setError(err);
    } finally {
      setIsUpdating(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800 pb-5">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl font-bold text-slate-100 flex items-center gap-2">
              <ShieldAlert className="w-5 h-5 text-red-400" />
              SOC Incident Triage & Alerts
            </h1>
            <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-red-950 text-red-300 border border-red-800/60 uppercase tracking-wider">
              Persistent Queue
            </span>
          </div>
          <p className="text-xs text-slate-400 mt-1">
            Escalated security alerts generated by configurable policy thresholds with immutable audit histories.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <span className="text-xs font-mono text-slate-400 bg-slate-900 px-3 py-1.5 rounded-xl border border-slate-800">
            {totalAlerts} Total Alerts
          </span>
        </div>
      </div>

      {/* Filter Bar */}
      <div className="flex flex-wrap items-center justify-between gap-3 bg-slate-900/60 p-4 rounded-xl border border-slate-800">
        <div className="flex flex-wrap items-center gap-2">
          <span className="text-xs font-semibold text-slate-400 flex items-center gap-1.5 mr-2">
            <Filter className="w-3.5 h-3.5 text-blue-400" /> Filters:
          </span>

          {/* Disposition Filter */}
          <select
            value={selectedDisposition}
            onChange={(e) => {
              setSelectedDisposition(e.target.value);
              setPage(1);
            }}
            className="bg-slate-950 border border-slate-800 rounded-lg px-3 py-1.5 text-xs text-slate-300 focus:outline-none focus:border-blue-500"
          >
            <option value="all">All Dispositions</option>
            <option value="OPEN">OPEN</option>
            <option value="INVESTIGATING">INVESTIGATING</option>
            <option value="RESOLVED">RESOLVED</option>
            <option value="FALSE_POSITIVE">FALSE_POSITIVE</option>
          </select>

          {/* Severity Filter */}
          <select
            value={selectedSeverity}
            onChange={(e) => {
              setSelectedSeverity(e.target.value);
              setPage(1);
            }}
            className="bg-slate-950 border border-slate-800 rounded-lg px-3 py-1.5 text-xs text-slate-300 focus:outline-none focus:border-blue-500"
          >
            <option value="all">All Severities</option>
            <option value="CRITICAL">CRITICAL</option>
            <option value="HIGH">HIGH</option>
            <option value="MEDIUM">MEDIUM</option>
            <option value="LOW">LOW</option>
          </select>
        </div>

        <button
          onClick={fetchAlerts}
          className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold rounded-lg transition-colors"
        >
          Refresh Queue
        </button>
      </div>

      {/* Error Alert */}
      {error && <ErrorAlert error={error} onDismiss={() => setError(null)} />}

      {/* Loading State */}
      {isLoading ? (
        <div className="bg-slate-900/40 border border-slate-800 rounded-2xl p-12 text-center">
          <LoadingSpinner message="Loading persistent security alerts..." size="lg" />
        </div>
      ) : (
        /* Alerts Table */
        <div className="border border-slate-800 rounded-xl overflow-hidden bg-slate-900/60 shadow-sm">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="border-b border-slate-800 bg-slate-950/60 text-slate-400 font-semibold">
                  <th className="py-3 px-4">Alert ID / Created</th>
                  <th className="py-3 px-3">Severity</th>
                  <th className="py-3 px-3">Disposition</th>
                  <th className="py-3 px-3">Threat & Risk</th>
                  <th className="py-3 px-4">Network Endpoints</th>
                  <th className="py-3 px-3">Policy Version</th>
                  <th className="py-3 px-4 text-right">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/60 font-mono">
                {alerts.map((al) => (
                  <tr
                    key={al.id}
                    onClick={() => handleOpenDetail(al.id)}
                    className="hover:bg-slate-800/40 transition-colors cursor-pointer"
                  >
                    {/* ID & Timestamp */}
                    <td className="py-3 px-4 text-slate-300 font-sans">
                      <div className="font-bold text-slate-200 text-[11px] font-mono">
                        {al.id.slice(0, 8)}...
                      </div>
                      <div className="text-[10px] text-slate-500 mt-0.5">
                        {new Date(al.created_at).toLocaleString()}
                      </div>
                    </td>

                    {/* Severity */}
                    <td className="py-3 px-3">
                      <SeverityBadge severity={al.severity} size="sm" />
                    </td>

                    {/* Disposition */}
                    <td className="py-3 px-3 font-sans">
                      <span
                        className={`inline-flex px-2 py-0.5 rounded text-[11px] font-semibold ${
                          al.disposition === 'OPEN'
                            ? 'bg-red-950/80 text-red-300 border border-red-700/60'
                            : al.disposition === 'INVESTIGATING'
                            ? 'bg-amber-950/80 text-amber-300 border border-amber-700/60'
                            : al.disposition === 'RESOLVED'
                            ? 'bg-emerald-950/80 text-emerald-300 border border-emerald-700/60'
                            : 'bg-slate-800 text-slate-400 border border-slate-700'
                        }`}
                      >
                        {al.disposition}
                      </span>
                    </td>

                    {/* Threat & Risk */}
                    <td className="py-3 px-3 font-sans">
                      <div className="font-bold text-slate-200 flex items-center gap-1.5">
                        <span className={al.predicted_family !== 'BENIGN' ? 'text-red-400' : 'text-slate-300'}>
                          {al.predicted_family}
                        </span>
                        <span className="text-slate-500 font-mono text-[11px]">({formatPercent(al.class_confidence)})</span>
                      </div>
                      <div className="text-[10px] text-slate-400 font-mono mt-0.5">
                        Risk Score: <span className="text-amber-400 font-bold">{al.risk_score}/100</span>
                      </div>
                    </td>

                    {/* Network Endpoints */}
                    <td className="py-3 px-4 text-slate-300">
                      <div className="font-semibold text-slate-200 flex items-center gap-1.5">
                        <span>{al.src_ip}:{al.src_port}</span>
                        <ArrowRight className="w-3 h-3 text-slate-500 inline" />
                        <span>{al.dst_ip}:{al.dst_port}</span>
                      </div>
                      <span className="text-[10px] text-slate-500 font-mono">
                        Protocol: {al.protocol_name}
                      </span>
                    </td>

                    {/* Policy */}
                    <td className="py-3 px-3 font-sans text-slate-400 text-[11px]">
                      {al.policy_version_applied}
                    </td>

                    {/* Action */}
                    <td className="py-3 px-4 text-right">
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          handleOpenDetail(al.id);
                        }}
                        className="px-3 py-1 bg-blue-600/80 hover:bg-blue-600 text-white rounded-lg text-xs font-semibold transition-colors"
                      >
                        Triage
                      </button>
                    </td>
                  </tr>
                ))}

                {alerts.length === 0 && (
                  <tr>
                    <td colSpan={7} className="py-12 text-center text-slate-500 font-sans">
                      No security alerts match current filter criteria.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>

          {/* Pagination Footer */}
          <div className="px-4 py-3 border-t border-slate-800 bg-slate-950/60 flex items-center justify-between text-xs text-slate-400">
            <div>
              Page <span className="font-mono text-slate-200">{page}</span> of{' '}
              <span className="font-mono text-slate-200">{totalPages}</span> ({totalAlerts} alerts)
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={() => setPage((p) => Math.max(1, p - 1))}
                disabled={page === 1}
                className="px-3 py-1 bg-slate-800 hover:bg-slate-700 disabled:opacity-40 disabled:pointer-events-none rounded-lg text-slate-300"
              >
                Previous
              </button>
              <button
                onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
                disabled={page === totalPages}
                className="px-3 py-1 bg-slate-800 hover:bg-slate-700 disabled:opacity-40 disabled:pointer-events-none rounded-lg text-slate-300"
              >
                Next
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Alert Detail & Triage Modal */}
      {selectedAlertDetail && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-in fade-in duration-150">
          <div className="bg-slate-900 border border-slate-800 rounded-2xl w-full max-w-3xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden">
            {/* Modal Header */}
            <div className="px-6 py-4 border-b border-slate-800 flex items-center justify-between bg-slate-950/60">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-red-950/80 border border-red-600/40 flex items-center justify-center text-red-400">
                  <ShieldAlert className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="text-base font-bold text-slate-100">
                    Incident Triage: <code className="text-red-400">{selectedAlertDetail.alert_type}</code>
                  </h3>
                  <p className="text-xs text-slate-400">
                    Alert ID: <code className="text-slate-300">{selectedAlertDetail.id}</code>
                  </p>
                </div>
              </div>
              <button
                onClick={() => setSelectedAlertDetail(null)}
                className="p-2 rounded-xl text-slate-400 hover:text-slate-200 hover:bg-slate-800 transition-colors"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Modal Body */}
            <div className="flex-1 overflow-y-auto p-6 space-y-6">
              {/* Context Cards */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div className="bg-slate-950/60 border border-slate-800 rounded-xl p-4 space-y-1">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400">Threat & Risk</span>
                  <div className="text-lg font-bold text-slate-100 flex items-center justify-between">
                    <span className="text-red-400">{selectedAlertDetail.predicted_family}</span>
                    <span className="text-xs font-mono text-slate-400">{formatPercent(selectedAlertDetail.class_confidence)}</span>
                  </div>
                  <div className="text-xs text-slate-400">Risk Score: <strong className="text-amber-400">{selectedAlertDetail.risk_score}/100</strong></div>
                </div>

                <div className="bg-slate-950/60 border border-slate-800 rounded-xl p-4 space-y-1">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400">Endpoints</span>
                  <div className="text-xs font-mono font-bold text-slate-200 truncate">
                    {selectedAlertDetail.src_ip}:{selectedAlertDetail.src_port}
                  </div>
                  <div className="text-xs font-mono text-slate-400 truncate">
                    <ArrowRight className="w-3 h-3 inline text-slate-500 mr-1" />
                    {selectedAlertDetail.dst_ip}:{selectedAlertDetail.dst_port} ({selectedAlertDetail.protocol_name})
                  </div>
                </div>

                <div className="bg-slate-950/60 border border-slate-800 rounded-xl p-4 space-y-1">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400">Current Status</span>
                  <div className="pt-0.5 flex items-center gap-2">
                    <SeverityBadge severity={selectedAlertDetail.severity} size="sm" />
                    <span className="text-xs font-bold text-slate-200">{selectedAlertDetail.disposition}</span>
                  </div>
                  <div className="text-[10px] text-slate-500">Policy: {selectedAlertDetail.policy_version_applied}</div>
                </div>
              </div>

              {/* Disposition Update Form */}
              <div className="bg-slate-950/80 border border-slate-800 rounded-xl p-5 space-y-4">
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-200 flex items-center gap-2">
                  <UserCheck className="w-4 h-4 text-blue-400" />
                  Update Workflow Disposition & Audit Log
                </h4>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  <div>
                    <label className="block text-xs text-slate-400 mb-1">New Disposition</label>
                    <select
                      value={newDisposition}
                      onChange={(e) => setNewDisposition(e.target.value)}
                      className="w-full bg-slate-900 border border-slate-800 rounded-lg px-3 py-2 text-xs text-slate-200 focus:outline-none focus:border-blue-500"
                    >
                      <option value="OPEN">OPEN (Unassigned)</option>
                      <option value="INVESTIGATING">INVESTIGATING (Under Review)</option>
                      <option value="RESOLVED">RESOLVED (True Incident Mitigated)</option>
                      <option value="FALSE_POSITIVE">FALSE_POSITIVE (Benign Pattern)</option>
                    </select>
                  </div>

                  <div>
                    <label className="block text-xs text-slate-400 mb-1">Analyst Identity / Actor ID</label>
                    <input
                      type="text"
                      value={analystActor}
                      onChange={(e) => setAnalystActor(e.target.value)}
                      className="w-full bg-slate-900 border border-slate-800 rounded-lg px-3 py-2 text-xs text-slate-200 focus:outline-none focus:border-blue-500"
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-xs text-slate-400 mb-1">Analyst Note / Rationale</label>
                  <textarea
                    rows={2}
                    placeholder="Document investigation findings, containment actions, or false-positive rationale..."
                    value={analystNote}
                    onChange={(e) => setAnalystNote(e.target.value)}
                    className="w-full bg-slate-900 border border-slate-800 rounded-lg px-3 py-2 text-xs text-slate-200 focus:outline-none focus:border-blue-500"
                  />
                </div>

                <div className="flex justify-end">
                  <button
                    onClick={handleUpdateDisposition}
                    disabled={isUpdating}
                    className="px-4 py-2 bg-blue-600 hover:bg-blue-500 disabled:opacity-50 text-white text-xs font-bold rounded-xl transition-colors flex items-center gap-2"
                  >
                    {isUpdating ? 'Saving Audit Record...' : 'Apply Triage State Update'}
                  </button>
                </div>
              </div>

              {/* Append-Only Audit History */}
              <div className="space-y-3">
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-300 flex items-center gap-2">
                  <History className="w-4 h-4 text-purple-400" />
                  Append-Only Lifecycle Audit Trail ({selectedAlertDetail.history.length} records)
                </h4>

                <div className="border border-slate-800 rounded-xl overflow-hidden bg-slate-950/40">
                  <table className="w-full text-left text-xs border-collapse font-sans">
                    <thead>
                      <tr className="border-b border-slate-800 bg-slate-900/60 text-slate-400 font-semibold">
                        <th className="py-2.5 px-4">Timestamp</th>
                        <th className="py-2.5 px-3">State Transition</th>
                        <th className="py-2.5 px-3">Actor</th>
                        <th className="py-2.5 px-4">Action Note / Rationale</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-800/60 font-mono text-[11px]">
                      {selectedAlertDetail.history.map((h) => (
                        <tr key={h.id} className="hover:bg-slate-900/40 transition-colors">
                          <td className="py-2.5 px-4 text-slate-400">
                            {new Date(h.timestamp).toLocaleString()}
                          </td>
                          <td className="py-2.5 px-3 font-sans">
                            <span className="text-slate-500">{h.previous_disposition || 'INIT'}</span>
                            <ArrowRight className="w-3 h-3 inline text-slate-600 mx-1.5" />
                            <strong className="text-slate-200">{h.new_disposition}</strong>
                          </td>
                          <td className="py-2.5 px-3 text-blue-400 font-bold">
                            {h.actor_id}
                          </td>
                          <td className="py-2.5 px-4 text-slate-300 font-sans">
                            {h.action_note || '—'}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>

            {/* Modal Footer */}
            <div className="px-6 py-3 border-t border-slate-800 bg-slate-950/60 flex justify-end">
              <button
                onClick={() => setSelectedAlertDetail(null)}
                className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold rounded-xl transition-colors"
              >
                Close Triage Modal
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
