"""Alert Service.

Evaluates configurable operational alert policies against security events and manages
incident lifecycle transitions.
"""

from __future__ import annotations

import logging
import uuid
from typing import Optional

from app.core.config import settings
from app.db.models.alert import Alert, AlertHistory
from app.db.models.security_event import SecurityEvent

logger = logging.getLogger(__name__)


class AlertService:
    """Evaluates security events against configurable triage policies to generate alerts."""

    @staticmethod
    def should_escalate_to_alert(event: SecurityEvent) -> tuple[bool, Optional[str], Optional[str]]:
        """Evaluate whether a SecurityEvent warrants an operational alert.
        
        Returns:
            (should_alert, alert_type, severity)
        """
        # Policy Rule 1: High-confidence known attack (predicted_family != BENIGN)
        if event.predicted_family != "BENIGN" and event.class_confidence >= settings.ALERT_CONFIDENCE_THRESHOLD:
            alert_type = f"KNOWN_ATTACK_{event.predicted_family}"
            return True, alert_type, event.severity

        # Policy Rule 2: High risk score exceeding configurable operational threshold
        if event.risk_score >= settings.ALERT_RISK_THRESHOLD:
            alert_type = "HIGH_RISK_INCIDENT" if event.predicted_family == "BENIGN" else f"ATTACK_{event.predicted_family}"
            return True, alert_type, event.severity

        # Policy Rule 3: Statistical unknown anomaly
        if settings.ALERT_ON_UNKNOWN_ANOMALY and event.triage_status == "UNKNOWN_ANOMALY":
            alert_type = "UNKNOWN_STATISTICAL_ANOMALY"
            return True, alert_type, event.severity

        return False, None, None

    @classmethod
    def create_alert_for_event(cls, event: SecurityEvent) -> Optional[Alert]:
        """Construct an Alert entity if the event qualifies under current policy."""
        should_alert, alert_type, severity = cls.should_escalate_to_alert(event)
        if not should_alert or not alert_type or not severity:
            return None

        alert = Alert(
            event_id=event.id,
            alert_type=alert_type,
            severity=severity,
            disposition="OPEN",
            analyst_notes=None,
            policy_version_applied=settings.ALERT_POLICY_VERSION,
        )

        # Initial append-only audit record
        AlertHistory(
            id=uuid.uuid4(),
            alert=alert,
            timestamp=event.event_timestamp,
            previous_disposition=None,
            new_disposition="OPEN",
            actor_id="system_triage_engine",
            action_note=f"Alert generated by policy {settings.ALERT_POLICY_VERSION} (Risk={event.risk_score}, Family={event.predicted_family})",
        )

        return alert
